#Feature Engineering

In [ ]:
import pandas as pd
import numpy as np

## Data Loading

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
filepath = '/content/drive/MyDrive/플젝/dataset.csv'

In [ ]:
data = pd.read_csv(filepath)

In [ ]:
data.head()

상태              공고번호  축  ... 중성화 여부                      특징        접수일시
0  종료(안락사)  전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1  종료(안락사)  전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
2  종료(안락사)  전남-영광-2020-00128  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
3  종료(안락사)  전북-부안-2020-00159  개  ...     미상       2개월령 믹스견 암컷, 바둑무늬  2020-05-09
4  종료(안락사)  전북-부안-2020-00158  개  ...     미상         2개월령 믹스견 수컷, 밤색  2020-05-09

[5 rows x 9 columns]

In [ ]:
data.info #[20132 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  ...                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  ...  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  ...  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
2      종료(안락사)   전남-영광-2020-00128  ...  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
3      종료(안락사)   전북-부안-2020-00159  ...       2개월령 믹스견 암컷, 바둑무늬  2020-05-09
4      종료(안락사)   전북-부안-2020-00158  ...         2개월령 믹스견 수컷, 밤색  2020-05-09
...        ...                ...  ...                     ...         ...
20127   종료(입양)  경기-남양주-2020-00580  ...     장식박힌 빨강색 가죽목줄착용.온순함  2020-04-06
20128   종료(입양)   경기-고양-2020-00337  ...                꼬리미용되어있음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  ...                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340  ...                      순함  2020-04-06
20131                        NaN  ...                     NaN         NaN

[20132 rows x 9 columns]>

## Data Preprocessing

In [ ]:
# '상태' 컬럼 기준으로 데이터 정리
data = data[data['상태'].str.startswith(('종료(자연사)', '종료(안락사)', '종료(반환)', '종료(입양)'))]
data.info #[19190 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  축  ... 중성화 여부                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
2      종료(안락사)   전남-영광-2020-00128  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
3      종료(안락사)   전북-부안-2020-00159  개  ...     미상       2개월령 믹스견 암컷, 바둑무늬  2020-05-09
4      종료(안락사)   전북-부안-2020-00158  개  ...     미상         2개월령 믹스견 수컷, 밤색  2020-05-09
...        ...                ... ..  ...    ...                     ...         ...
20126  종료(자연사)  경기-남양주-2020-00581  개  ...      예   체구가크고 온순함.움직이지않고 먹지않음  2020-04-06
20127   종료(입양)  경기-남양주-2020-00580  개  ...    아니오     장식박힌 빨강색 가죽목줄착용.온순함  2020-04-06
20128   종료(입양)   경기-고양-2020-00337  개  ...      예                꼬리미용되어있음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  개  ...     미상                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340

In [ ]:
# '축' 컬럼 기준으로 데이터 정리
data = data[data['축'].str.startswith('개')]
data.info #[16410 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  축  ... 중성화 여부                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
2      종료(안락사)   전남-영광-2020-00128  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
3      종료(안락사)   전북-부안-2020-00159  개  ...     미상       2개월령 믹스견 암컷, 바둑무늬  2020-05-09
4      종료(안락사)   전북-부안-2020-00158  개  ...     미상         2개월령 믹스견 수컷, 밤색  2020-05-09
...        ...                ... ..  ...    ...                     ...         ...
20126  종료(자연사)  경기-남양주-2020-00581  개  ...      예   체구가크고 온순함.움직이지않고 먹지않음  2020-04-06
20127   종료(입양)  경기-남양주-2020-00580  개  ...    아니오     장식박힌 빨강색 가죽목줄착용.온순함  2020-04-06
20128   종료(입양)   경기-고양-2020-00337  개  ...      예                꼬리미용되어있음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  개  ...     미상                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340

In [ ]:
# '성별' 컬럼 기준으로 데이터 정리
data = data[data['성'].str.startswith(('수컷', '암컷'))]
data.info #[16229 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  축  ... 중성화 여부                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
2      종료(안락사)   전남-영광-2020-00128  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
3      종료(안락사)   전북-부안-2020-00159  개  ...     미상       2개월령 믹스견 암컷, 바둑무늬  2020-05-09
4      종료(안락사)   전북-부안-2020-00158  개  ...     미상         2개월령 믹스견 수컷, 밤색  2020-05-09
...        ...                ... ..  ...    ...                     ...         ...
20126  종료(자연사)  경기-남양주-2020-00581  개  ...      예   체구가크고 온순함.움직이지않고 먹지않음  2020-04-06
20127   종료(입양)  경기-남양주-2020-00580  개  ...    아니오     장식박힌 빨강색 가죽목줄착용.온순함  2020-04-06
20128   종료(입양)   경기-고양-2020-00337  개  ...      예                꼬리미용되어있음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  개  ...     미상                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340

In [ ]:
# '품종' 컬럼 기준으로 데이터 정리
species_option = ['골든 리트리버',
 '그레이 하운드',
 '그레이트 덴',
 '그레이트 피레니즈',
 '기타',
 '꼬똥 드 뚤레아',
 '네오폴리탄 마스티프',
 '노르포크 테리어',
 '노리치 테리어',
 '뉴펀들랜드',
 '닥스훈트',
 '달마시안',
 '댄디 딘몬트 테리어',
 '도고 까니리오',
 '도고 아르젠티노',
 '도고 아르젠티노',
 '도베르만',
 '도사',
 '동경견',
 '라브라도 리트리버',
 '라사 압소',
 '라이카',
 '래빗 닥스훈드',
 '랫 테리어',
 '레이크랜드 테리어',
 '로디지안 리즈백',
 '로트바일러',
 '롯트와일러',
 '마리노이즈',
 '마스티프',
 '말라뮤트',
 '말티즈',
 '맨체스터테리어',
 '미니어쳐 닥스훈트',
 '미니어쳐 불 테리어',
 '미니어쳐 슈나우저',
 '미니어쳐 푸들',
 '미니어쳐 핀셔',
 '미디엄 푸들',
 '미텔 스피츠',
 '믹스견',
 '바센지',
 '바셋 하운드',
 '버니즈 마운틴 독',
 '베들링턴 테리어',
 '벨기에 그로넨달',
 '벨기에 쉽독',
 '벨기에 테뷰런',
 '벨지안 셰퍼드 독',
 '보더 콜리',
 '보르조이',
 '보스턴 테리어',
 '복서',
 '볼로네즈',
 '부비에 데 플랑드르',
 '불 테리어',
 '불독',
 '브뤼셀그리펀',
 '브리타니 스파니엘',
 '블랙 테리어',
 '비글',
 '비숑 프리제',
 '비어디드 콜리',
 '비즐라',
 '빠삐용',
 '사모예드',
 '살루키',
 '삽살개',
 '샤페이',
 '세인트 버나드',
 '센트럴 아시안 오브차카',
 '셔틀랜드 쉽독',
 '셰퍼드',
 '슈나우져',
 '스코티쉬 테리어',
 '스코티시 디어하운드',
 '스탠다드 푸들',
 '스테포드셔불테리어',
 '스피츠',
 '시바',
 '시베리안 허스키',
 '시베리안라이카',
 '시잉프랑세즈',
 '시츄',
 '시코쿠',
 '실리햄 테리어',
 '실키테리어',
 '아나톨리안 셰퍼드',
 '아메리칸 불독',
 '아메리칸 스태퍼드셔 테리어',
 '아메리칸 아키다',
 '아메리칸 에스키모',
 '아메리칸 코카 스파니엘',
 '아메리칸 핏불 테리어',
 '아메리칸불리',
 '아이리쉬 레드 앤 화이트 세터',
 '아이리쉬 세터',
 '아이리쉬 울프 하운드',
 '아이리쉬소프트코튼휘튼테리어',
 '아키다',
 '아프간 하운드',
 '알라스칸 말라뮤트',
 '에어델 테리어',
 '오브차카',
 '오스트랄리안 셰퍼드 독',
 '오스트랄리안 캐틀 독',
 '올드 잉글리쉬 불독',
 '올드 잉글리쉬 쉽독',
 '와이마라너',
 '와이어 폭스 테리어',
 '요크셔 테리어',
 '울프독',
 '웨스트 시베리언 라이카',
 '웨스트하이랜드화이트테리어',
 '웰시 코기 카디건',
 '웰시 코기 펨브로크',
 '웰시 테리어',
 '이탈리안 그레이 하운드',
 '잉글리쉬 세터',
 '잉글리쉬 스프링거 스파니엘',
 '잉글리쉬 코카 스파니엘',
 '잉글리쉬 포인터',
 '자이언트 슈나우져',
 '재패니즈 스피츠',
 '잭 러셀 테리어',
 '저먼 셰퍼드 독',
 '저먼 와이어헤어드 포인터',
 '저먼 포인터',
 '제주개',
 '제페니즈칭',
 '진도견',
 '차우차우',
 '차이니즈 크레스티드 독',
 '치와와',
 '카레리안 베어독',
 '카이훗',
 '캐벌리어 킹 찰스 스파니엘',
 '케니스펜더',
 '케리 블루 테리어',
 '케언 테리어',
 '케인 코르소',
 '코리아 트라이 하운드',
 '코리안 마스티프',
 '코카 스파니엘',
 '코카 푸',
 '코카시안오브차카',
 '콜리',
 '클라인스피츠',
 '키슈',
 '키스 훈드',
 '토이 맨체스터 테리어',
 '토이 푸들',
 '티베탄 마스티프',
 '파라오 하운드',
 '파슨 러셀 테리어',
 '팔렌',
 '퍼그',
 '페키니즈',
 '페터데일테리어',
 '포메라니안',
 '포인터',
 '폭스테리어',
 '푸들',
 '풀리',
 '풍산견',
 '프레사까나리오',
 '프렌치 불독',
 '프렌치 브리타니',
 '플랫 코티드 리트리버',
 '플롯하운드',
 '피레니안 마운틴 독',
 '필라 브라질레오',
 '핏불테리어',
 '허배너스',
 '화이트리트리버',
 '화이트테리어',
 '휘펫']

data = data[data['품종'].isin(species_option)]
data.info #[16076 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  축  ... 중성화 여부                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
2      종료(안락사)   전남-영광-2020-00128  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
3      종료(안락사)   전북-부안-2020-00159  개  ...     미상       2개월령 믹스견 암컷, 바둑무늬  2020-05-09
4      종료(안락사)   전북-부안-2020-00158  개  ...     미상         2개월령 믹스견 수컷, 밤색  2020-05-09
...        ...                ... ..  ...    ...                     ...         ...
20126  종료(자연사)  경기-남양주-2020-00581  개  ...      예   체구가크고 온순함.움직이지않고 먹지않음  2020-04-06
20127   종료(입양)  경기-남양주-2020-00580  개  ...    아니오     장식박힌 빨강색 가죽목줄착용.온순함  2020-04-06
20128   종료(입양)   경기-고양-2020-00337  개  ...      예                꼬리미용되어있음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  개  ...     미상                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340

In [ ]:
# '털색' 컬럼 기준으로 데이터 정리
data = data[(data['털색']=='흰색')|(data['털색']=='흰')|(data['털색']=='크림색')|(data['털색']=='검정색')|(data['털색']=='검정')|(data['털색']=='검은색')|(data['털색']=='갈색')|(data['털색']=='갈')|(data['털색']=='황색')]
data.info #[8359 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  축  ... 중성화 여부                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
5      종료(안락사)   전북-부안-2020-00157  개  ...     미상         2개월령 믹스견 수컷, 흰색  2020-05-09
6      종료(안락사)   전북-부안-2020-00156  개  ...     미상             2개월령 믹스견 수컷  2020-05-09
7      종료(안락사)   전북-부안-2020-00170  개  ...     미상             2개월령 믹스견 수컷  2020-05-09
...        ...                ... ..  ...    ...                     ...         ...
20120   종료(입양)   경기-하남-2020-00172  개  ...      예                    2달얘기  2020-04-06
20124   종료(입양)  경기-남양주-2020-00583  개  ...    아니오             어린강아지나 체구가큼  2020-04-06
20125  종료(안락사)  경기-남양주-2020-00582  개  ...    아니오     털이길고 거동이 불편해 움직이지않음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  개  ...     미상                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340

In [ ]:
#결측값 처리
data = data.fillna('.')
data.info #[8359 rows x 9 columns]

<bound method DataFrame.info of             상태               공고번호  축  ... 중성화 여부                      특징        접수일시
0      종료(안락사)   전남-영광-2020-00130  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1      종료(안락사)   전남-영광-2020-00129  개  ...    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
5      종료(안락사)   전북-부안-2020-00157  개  ...     미상         2개월령 믹스견 수컷, 흰색  2020-05-09
6      종료(안락사)   전북-부안-2020-00156  개  ...     미상             2개월령 믹스견 수컷  2020-05-09
7      종료(안락사)   전북-부안-2020-00170  개  ...     미상             2개월령 믹스견 수컷  2020-05-09
...        ...                ... ..  ...    ...                     ...         ...
20120   종료(입양)   경기-하남-2020-00172  개  ...      예                    2달얘기  2020-04-06
20124   종료(입양)  경기-남양주-2020-00583  개  ...    아니오             어린강아지나 체구가큼  2020-04-06
20125  종료(안락사)  경기-남양주-2020-00582  개  ...    아니오     털이길고 거동이 불편해 움직이지않음  2020-04-06
20129   종료(입양)   경기-고양-2020-00336  개  ...     미상                  귀끝털 황색  2020-04-06
20130   종료(입양)   경기-안산-2020-00340

In [ ]:
#품종 확인
species = data['품종'].drop_duplicates()
species_list = species.values.tolist()
print(len(species_list))
species_list

58


['믹스견',
 '푸들',
 '말티즈',
 '포메라니안',
 '진도견',
 '골든 리트리버',
 '스피츠',
 '라브라도 리트리버',
 '그레이트 피레니즈',
 '풍산견',
 '케인 코르소',
 '코리아 트라이 하운드',
 '삽살개',
 '페키니즈',
 '코카 스파니엘',
 '사모예드',
 '비글',
 '요크셔 테리어',
 '비숑 프리제',
 '프렌치 불독',
 '그레이 하운드',
 '치와와',
 '보더 콜리',
 '아프간 하운드',
 '닥스훈트',
 '셰퍼드',
 '차우차우',
 '아메리칸 코카 스파니엘',
 '미니어쳐 핀셔',
 '잉글리쉬 코카 스파니엘',
 '슈나우져',
 '시바',
 '웰시 코기 펨브로크',
 '불독',
 '재패니즈 스피츠',
 '동경견',
 '샤페이',
 '도베르만',
 '벨기에 그로넨달',
 '스탠다드 푸들',
 '말라뮤트',
 '시베리안 허스키',
 '기타',
 '페터데일테리어',
 '시츄',
 '웰시 코기 카디건',
 '토이 푸들',
 '미니어쳐 푸들',
 '보스턴 테리어',
 '올드 잉글리쉬 쉽독',
 '바센지',
 '로트바일러',
 '핏불테리어',
 '제주개',
 '올드 잉글리쉬 불독',
 '코카시안오브차카',
 '케언 테리어',
 '마스티프']

In [ ]:
#털색 확인
color = data['털색'].drop_duplicates()
color_list = color.values.tolist()
print(len(color_list))
color_list

9


['흰색', '갈색', '흰', '검정', '갈', '검정색', '크림색', '황색', '검은색']

In [ ]:
#특징 확인
comment = data['특징'].drop_duplicates()
comment_list = comment.values.tolist()
print(len(comment_list))
comment_list

3178


['마을에서 돌아다닌 다는 신고로 포획 보호',
 '2개월령 믹스견 수컷, 흰색',
 '2개월령 믹스견 수컷',
 '2개월령 암컷, 흰색 믹스견',
 '야윔, 우전지 골절 상태 오래됨',
 '생후 2개월령',
 '털관리 안됨. 가위로 대충 털 자름.',
 '이빨이 다 &#50026;음',
 '핑크색 목줄만 착용',
 '634',
 '순하고 잘따름,관리됨,활발함',
 '미용 및 관리됨,목줄착용,순함',
 '비맞으며 초등학교 한가운데서 배회..멀미해서 침흘림.순함.',
 '흰색, 겁이 많음.',
 '흰색, 진드기있음, 성격 온순.',
 '연두색 목걸이. 눈물자국. 코갈검. 겁있음. 사람따름. 얌전함. 단미안됨.',
 '없음',
 '주황색 목줄, 쇠로된 은색 목걸이 착용',
 '털복실 순한 스피츠',
 '어미와 같이 구조됨',
 '흰색',
 '양눈백내장.양귀쫑긋.코갈색.치석심함.겁있음.소심함.사람따름.',
 '현재 발정중, 양호함. 가출로 보여짐',
 '양귀쫑긋. 코검정. 겁많음. 소심함. 꼬리단미안됨. 털상태 양호.',
 '옷착용, 미용됨',
 '순하고사람잘따름,피부귀상태양호.칩없음',
 '남천강변에서 배회',
 '765호(관리) 411호(공고) 온순함',
 '764호(관리) 410호(공고) 착함',
 '채리아이, 겁이다소 있으나 온순함',
 '겁이많음',
 '겁이 다소 있으나, 온순함',
 '경계심이 많고 사나움',
 '온순함',
 'GPS착용, 온순함',
 '좌측다리 부상, 경계심이 다소있음',
 '인식표있으나 주인전화 안받음',
 '강아지',
 '순함',
 '칩있음.',
 '20-0669 눈이',
 '겁 많음',
 '흰색을 띄고 있음',
 '사나움',
 '까칠함',
 '5마리 중에서 가장 온순함',
 '5마리 중에서 가장 까칠함 그러나 그것이 매력',
 '5마리 중에서 가장 애교를 부림',
 '유기견이 빈집에 들어와서 세끼 출산 어미견 포획 실패.',
 '아직 손을 타지 않아서 조금은 성깔을 부림',
 '마을에 돌면서 운동이나 산책하는 아이와 주부들에게 위협

In [ ]:
data_numpy = data.to_numpy() #(16229, 9)
print(data_numpy.shape)
print(data_numpy[0])

(8359, 9)
['종료(안락사)' '전남-영광-2020-00130' '개' '믹스견' '흰색' '수컷' '아니오'
 '마을에서 돌아다닌 다는 신고로 포획 보호' '2020-05-09']


In [ ]:
#data2 = pd.get_dummies

상태 공고번호  축   품종 털색   성 중성화 여부                      특징        접수일시
0  종료(안락사)   전남  개  믹스견  흰  수컷    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
1  종료(안락사)   전남  개  믹스견  흰  수컷    아니오  마을에서 돌아다닌 다는 신고로 포획 보호  2020-05-09
5  종료(안락사)   전북  개  믹스견  흰  수컷     미상         2개월령 믹스견 수컷, 흰색  2020-05-09
6  종료(안락사)   전북  개  믹스견  흰  수컷     미상             2개월령 믹스견 수컷  2020-05-09
7  종료(안락사)   전북  개  믹스견  흰  수컷     미상             2개월령 믹스견 수컷  2020-05-09

## Feature Extraction

In [ ]:
# 상태(라벨)
y = []
for i in range(data_numpy.shape[0]):
  if data_numpy[i][0].endswith(('(자연사)', '(안락사)')):
    data_numpy[i][0] = 0
    y.append(0)

  else:
    data_numpy[i][0] = 1
    y.append(1)
y = np.array(y)   
print(y.shape)

In [ ]:
#공고번호
for i in range(data_numpy.shape[0]):
  location = data_numpy[i][1]
  data_numpy[i][1] = location[:2]
  
from sklearn import preprocessing 

label_encoder = preprocessing.LabelEncoder() 
onehot_encoder = preprocessing.OneHotEncoder()

x_location = label_encoder.fit_transform(data_numpy[:,1])
x_location = x_location.reshape(-1,1) 
x_location = onehot_encoder.fit_transform(x_location).toarray()
#x_ㅣocation_recovery = np.argmax(x_location, axis=1).reshape(-1,1)
print(x_location.shape)

(8359, 17)


In [ ]:
#품종
from sklearn import preprocessing 

label_encoder = preprocessing.LabelEncoder() 
onehot_encoder = preprocessing.OneHotEncoder()

x_species = label_encoder.fit_transform(data_numpy[:,3])
x_species = x_species.reshape(-1,1) 
x_species = onehot_encoder.fit_transform(x_species).toarray()
#x_ㅣocation_recovery = np.argmax(x_species, axis=1).reshape(-1,1)
print(x_species.shape)

(8359, 58)


In [ ]:
#털색
for i in range(data_numpy.shape[0]):
  color = data_numpy[i][4]
  if (color=='흰색') or (color=='흰') or (color=='크림색'):
    data_numpy[i][4] = '흰'
  if (color=='검정색') or (color=='검정') or (color=='검은색'):
    data_numpy[i][4] = '검'
  if (color=='갈색') or (color=='갈') or (color=='황색') :
    data_numpy[i][4] = '황'
  
  
x_color = label_encoder.fit_transform(data_numpy[:,4])
x_color = x_color.reshape(-1,1) 
x_color = onehot_encoder.fit_transform(x_color).toarray()
#x_color_recovery = np.argmax(x_color, axis=1).reshape(-1,1)
print(x_color.shape)

(8359, 3)


In [ ]:
#성
from sklearn import preprocessing 

label_encoder = preprocessing.LabelEncoder() 
onehot_encoder = preprocessing.OneHotEncoder()

x_sex = label_encoder.fit_transform(data_numpy[:,5])
x_sex = x_sex.reshape(-1,1) 
x_sex = onehot_encoder.fit_transform(x_sex).toarray()
#x_sex_recovery = np.argmax(x_sex, axis=1).reshape(-1,1)
print(x_sex.shape)

(8359, 2)


In [ ]:
#중성화 여부
from sklearn import preprocessing 

label_encoder = preprocessing.LabelEncoder() 
onehot_encoder = preprocessing.OneHotEncoder()

x_neutralized = label_encoder.fit_transform(data_numpy[:,6])
x_neutralized = x_neutralized.reshape(-1,1) 
x_neutralized = onehot_encoder.fit_transform(x_neutralized).toarray() #미상 = [1., 0., 0.], 아니요 = [0., 1., 0.], 네= [0., 0., 1.]
#x_sex_recovery = np.argmax(x_neutralized, axis=1).reshape(-1,1)
print(x_neutralized.shape)

(8359, 3)


In [ ]:
neg_sign_list = ['야윔', '골절', '마름', '영양', '침', '진드기', '경계', '눈물', '오염', '겁', '거친', '비틀', '기력', '기립', '통증',
            '식욕', '눈곱', '불량', '슬개골', '백내장', '치석', '궤양', '양성', '채리아이', '체리아이' '사나운', '사나움', '부상',
            '구토', '기형', '위협', '굶주림', '탈모', '상처', '으르렁', '짖음', '비명', '입질', '포악', '마비', '홍역', '승저증', 
            '폐렴', '증상', '감염', '증후군', '사고', '심각', '절음', '외이염', '출혈', '보행', '불안', '탈수', '공격', '비만', 
            '탈진', '설사', '고름', '노령', '노견', '엉킴', '교상', '결막염', '파행', '불편', '병', '종양', '사마귀', '질환', 
            '손상', '탈장', '염좌', '절단', '외상', '위축', '허약', '환부', '괴사', '염증']

pos_sign_list = ['순', '따름', '괸리됨', '활발', '좋아하며', '좋아함', '양호', '미용', '귀여운', '귀엽게', '귀엽고', '귀여움', '복실',
            '포동', '착한', '착하게', '착하고', '착함', '깨끗', '애교', '건강', '이쁜', '이쁘게', '이쁘고', '이쁨', '영리', '백신', 
            '음성', '얌전', '개월', '어린', '어리게', '어리고', '어림', '예쁜', '예쁘게', '예쁘고', '예쁨', '사회성', '사랑', '훈련']

In [ ]:
#특징
neg_score_list = []
pos_score_list = []

for i in range(data_numpy.shape[0]):
  comment = data_numpy[i][7]
  neg_score = 0
  pos_score = 0
  for sign in neg_sign_list:
    if sign in comment:
      neg_score += 1
  neg_score_list.append(neg_score)
  np.append(data_numpy, neg_score)

  for sign in pos_sign_list:
    if sign in comment:
      pos_score += 1
  pos_score_list.append(pos_score)
  np.append(data_numpy, pos_score)

d = np.array([])
np.append(d, np.array(neg_score_list))
np.append(d, np.array(pos_score_list))
x_neg = np.array(neg_score_list)
x_pos = np.array(pos_score_list)
print(x_neg.shape)
print(x_pos.shape)
print(x_neg[:5])
print(x_pos[:5])

(8359,)
(8359,)
[0 0 0 0 0]
[0 0 1 1 1]


In [ ]:
d = np.array([[]])
d = np.append(d, , axis=1)
d = np.append(d, np.array(pos_score_list), axis=1)

ValueError: ignored

In [ ]:
data_numpy[0]

array([0, '전남', '개', '믹스견', '흰', '수컷', '아니오', '마을에서 돌아다닌 다는 신고로 포획 보호',
       '2020-05-09'], dtype=object)

In [ ]:
df = pd.DataFrame({'label': y, 'location': data_numpy[:,1], 'species': data_numpy[:,3], 'color': data_numpy[:,4], 'sex': data_numpy[:,5], 'neutralized': data_numpy[:,6], 'neg_score': x_neg, 'pos_socre': x_pos})

In [ ]:
df.head()

label location species color sex neutralized  neg_score  pos_socre
0      0       전남     믹스견     흰  수컷         아니오          0          0
1      0       전남     믹스견     흰  수컷         아니오          0          0
2      0       전북     믹스견     흰  수컷          미상          0          1
3      0       전북     믹스견     흰  수컷          미상          0          1
4      0       전북     믹스견     흰  수컷          미상          0          1

In [ ]:
df2 = pd.get_dummies(df)

In [ ]:
df2.to_csv('sample.csv', encoding='utf-8-sig')

In [ ]:
pd.to_csv(df2)

In [ ]:
"""
#접수일시
for i in range(data_numpy.shape[0]):
  date = data_numpy[i][8]
  month = date[5:7]
  if month in ['03','04','05']:
    data_numpy[i][8] =' 봄'
  if month in ['06','07','08']:
    data_numpy[i][8] =' 여름'
  if month in ['09','10','11']:
    data_numpy[i][8] = '가을'
  if month in ['12','01','02']:
    data_numpy[i][8] =' 겨울'

from sklearn import preprocessing 

label_encoder = preprocessing.LabelEncoder() 
onehot_encoder = preprocessing.OneHotEncoder()

x_season = label_encoder.fit_transform(data_numpy[:,8])
x_season = x_season.reshape(-1,1) 
x_season = onehot_encoder.fit_transform(x_season).toarray() #미상 = [1., 0., 0.], 아니요 = [0., 1., 0.], 네= [0., 0., 1.]
#x_sex_recovery = np.argmax(x_season, axis=1).reshape(-1,1)
print(x_season.shape)
"""

"\n#접수일시\nfor i in range(data_numpy.shape[0]):\n  date = data_numpy[i][8]\n  month = date[5:7]\n  if month in ['03','04','05']:\n    data_numpy[i][8] =' 봄'\n  if month in ['06','07','08']:\n    data_numpy[i][8] =' 여름'\n  if month in ['09','10','11']:\n    data_numpy[i][8] = '가을'\n  if month in ['12','01','02']:\n    data_numpy[i][8] =' 겨울'\n\nfrom sklearn import preprocessing \n\nlabel_encoder = preprocessing.LabelEncoder() \nonehot_encoder = preprocessing.OneHotEncoder()\n\nx_season = label_encoder.fit_transform(data_numpy[:,8])\nx_season = x_season.reshape(-1,1) \nx_season = onehot_encoder.fit_transform(x_season).toarray() #미상 = [1., 0., 0.], 아니요 = [0., 1., 0.], 네= [0., 0., 1.]\n#x_sex_recovery = np.argmax(x_season, axis=1).reshape(-1,1)\nprint(x_season.shape)\n"

In [ ]:
#data_numpy = data_numpy[:, :8]
data_numpy_ = np.

array([0, '전남', '개', '믹스견', '흰', '수컷', '아니오', '마을에서 돌아다닌 다는 신고로 포획 보호',
       '2020-05-09'], dtype=object)

In [ ]:
df = pd.DataFrame(data_numpy)

In [ ]:
df.head()

0   1  2    3  4   5    6                       7
0  0  전남  개  믹스견  흰  수컷  아니오  마을에서 돌아다닌 다는 신고로 포획 보호
1  0  전남  개  믹스견  흰  수컷  아니오  마을에서 돌아다닌 다는 신고로 포획 보호
2  0  전북  개  믹스견  흰  수컷   미상         2개월령 믹스견 수컷, 흰색
3  0  전북  개  믹스견  흰  수컷   미상             2개월령 믹스견 수컷
4  0  전북  개  믹스견  흰  수컷   미상             2개월령 믹스견 수컷

In [ ]:
x_sex[0]

array([1., 0.])

In [ ]:
x_species[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x_location[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [ ]:
data_ = []
for i in range(data_numpy.shape[0]):
  data_.append([x_species[i], x_location[i], x_color[i], x_sex[i], x_neutralized[i], x_neg[i], x_pos[i]])

In [ ]:
data_ = np.array(data_)
print(data_.shape)

(8359, 7)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [ ]:
data_[0]

array([array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.]),
       array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]),
       array([0., 0., 1.]), array([1., 0.]), array([0., 1., 0.]), 0, 0],
      dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X = df2.drop('label', axis=1)
y = df2[['label']]
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred)) 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


              precision    recall  f1-score   support

           0       0.69      0.80      0.74       807
           1       0.78      0.66      0.72       865

    accuracy                           0.73      1672
   macro avg       0.74      0.73      0.73      1672
weighted avg       0.74      0.73      0.73      1672

